### ISSUE TITLE
Cannot install codacy-cli

### ISSUE THREAD

**Issue by muktaa** [codacy/codacy-cli#1]
Hi, 
I tried to install codacy-cli using npm. It seemed to be successful. But i am not able to find where the `codacy` exec is located. 

**Error**
    
    $ codacy
    codacy: command not found

**npm install codacy:**

    $ sudo npm install codacy-cli
    npm http GET https://registry.npmjs.org/codacy-cli
    npm http 304 https://registry.npmjs.org/codacy-cli
    npm http GET https://registry.npmjs.org/sync-prompt/0.2.2
    npm http GET https://registry.npmjs.org/commander/2.2.0
    npm http GET https://registry.npmjs.org/extend/1.2.1
    npm http GET https://registry.npmjs.org/http-sync/0.0.4
    npm http GET https://registry.npmjs.org/json-table/0.1.3
    npm http GET https://registry.npmjs.org/pkginfo/0.3.0
    npm http 304 https://registry.npmjs.org/extend/1.2.1
    npm http 304 https://registry.npmjs.org/http-sync/0.0.4
    npm http 304 https://registry.npmjs.org/sync-prompt/0.2.2
    npm http 304 https://registry.npmjs.org/commander/2.2.0
    npm http 304 https://registry.npmjs.org/json-table/0.1.3
    npm http 304 https://registry.npmjs.org/pkginfo/0.3.0

    > sync-prompt@0.2.2 install /home/ubuntu/node_modules/codacy-cli/node_modules/sync-prompt
    > node-gyp rebuild

    > http-sync@0.0.4 install /home/ubuntu/node_modules/codacy-cli/node_modules/http-sync
    > node-gyp rebuild

    npm http GET https://registry.npmjs.org/cli-table
    npm http GET https://registry.npmjs.org/async
    npm http 304 https://registry.npmjs.org/cli-table
    npm http 304 https://registry.npmjs.org/async
    make: Entering directory `/home/ubuntu/node_modules/codacy-cli/node_modules/sync-prompt/build'
      CXX(target) Release/obj.target/sync_prompt/src/sync_prompt.o
    npm http GET https://registry.npmjs.org/colors/0.3.0
    make: Entering directory `/home/ubuntu/node_modules/codacy-cli/node_modules/http-sync/build'
      CXX(target) Release/obj.target/curllib/curllib.o
    npm http 304 https://registry.npmjs.org/colors/0.3.0
      SOLINK_MODULE(target) Release/obj.target/sync_prompt.node
      SOLINK_MODULE(target) Release/obj.target/sync_prompt.node: Finished
      COPY Release/sync_prompt.node
    make: Leaving directory `/home/ubuntu/node_modules/codacy-cli/node_modules/sync-prompt/build'
      SOLINK_MODULE(target) Release/obj.target/curllib.node
      SOLINK_MODULE(target) Release/obj.target/curllib.node: Finished
      COPY Release/curllib.node
    make: Leaving directory `/home/ubuntu/node_modules/codacy-cli/node_modules/http-sync/build'
    codacy-cli@0.1.1 node_modules/codacy-cli
    ├── extend@1.2.1
    ├── commander@2.2.0
    ├── pkginfo@0.3.0
    ├── json-table@0.1.3 (async@0.2.10, cli-table@0.2.0)
    ├── sync-prompt@0.2.2
    └── http-sync@0.0.4`

**Comment by rtfpessoa** [comment]
Hi Mukta,

I found that our documentation is missing a flag to install the plugin globally.

I just corrected the command. Can you try with:

`npm install -g codacy-cli`

Let me know if you have any other issues.
