### ISSUE TITLE
Error while running codacy-cli

### ISSUE THREAD

**Issue by muktaa** [codacy/codacy-cli#2]
I get the following error when I try to run codacy-cli:

    $ codacy
    /usr/bin/env: node: No such file or directory

**Comment by caxaria** [comment]
Hi Mukta,

Can you confirm me that you have node correctly installed? Running this should provide details:

node --version

**Comment by muktaa** [comment]
My bad. I missed installing node, did the documentation change? I remember seeing it before, but dont see it now.
